workflows:
  android-workflow:
    name: Android Release Build
    max_build_duration: 60
    instance_type: linux_x2
    working_directory: apps/mobile
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Build APK
        script: |
          flutter build apk --release --dart-define=API_URL=$API_URL
    
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
